**Project:** Data Mining II (2025/26)

**Group Number:** 12

**Members:**
- Beatriz Boura - 20250272
- Dinis Gaspar - 20221869
- Margarida Cruz - 20221929

**Project Overview**

In recent years, nonprofit organizations have faced a growing challenge: while charitable causes have multiplied, public tolerance for repeated, generic solicitations has significantly decreased, often leading to donor fatigue and long-term disengagement. To address this issue, the Civic Support Alliance (CSA)—a federation representing multiple humanitarian and social aid programs—seeks to modernize its fundraising strategy. Rather than launching blanket campaigns across their entire database, the organization aims to transition to a highly targeted approach. The goal is to maximize operational efficiency and maintain donor respect by contacting fewer, but more receptive, individuals. 

As data scientists, our team has been tasked with building a predictive machine learning system using historical demographic, interaction, and donation data accumulated from past campaigns. The primary objective is to accurately answer a fundamental question: Will this person donate if contacted? 

**Notebook Introduction**

In this notebook, we will develop Neural Networks, we will find parameter regions using our hold-out method splits as explained in the Modeling Tools notebook to test and we will then perform a parameter search to try and maximize performances.

Note: All of the code that is used to produce plots or results which takes significant time to run is present in Markdown cells and plots are shown from saved files of the code when it was run.

**Benchmarks**

As the goal of this project is to help the CSA create and improve a targeted approach to donors with the goal of maximizing donations, we will use 2 baseline benchmarks as the minimum any model must achieve to be a good model:
+ Random prediction, which in a dataset with the imbalance present in the CSA's data yield an **F1-Score of ~0.34**
+ Predicting all 1, which is essentially, telling the CSA to keep sending out the camapaign to everyone. This is obviously not the desire of the CSA and as such the goal is to create models that can avoid this. Predicting all 1 in a dataset with this imbalance yields an **F1-Score of 0.4**

# Imports

In this section we're importing everything we need, libraries and tools.

In [23]:
from utils_modeling import (OutlierClipper, CategoricalFeatureSelector, NumericalFeatureSelector, FeatureEngineer, DataCleaner, run_parameter_search)
import os
# Adding this ensures that the magic command only runs once (the first time)
if os.getcwd().split('\\')[-1] != 'DM2_Project':
    %cd ..
import numpy as np
import pandas as pd
from sklearn.model_selection import TunedThresholdClassifierCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import OneHotEncoder, RobustScaler, MinMaxScaler, PowerTransformer
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from sklearn.neural_network import MLPClassifier
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import f1_score
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import pickle
import warnings
warnings.filterwarnings("ignore")
SEED=23
pd.options.display.max_columns = None

In [24]:
train = pd.read_csv('Files/donors_train.csv')
test = pd.read_csv('Files/donors_test.csv')

X_train_preprocessed = pd.read_pickle('Files/Pickle Files/X_train_preprocessed.pkl')
X_val_preprocessed = pd.read_pickle('Files/Pickle Files/X_val_preprocessed.pkl')
y_train = pd.read_pickle('Files/Pickle Files/y_train.pkl')
y_val = pd.read_pickle('Files/Pickle Files/y_val.pkl')

with open('Files/Pickle Files/model_testing_skf.pkl', 'rb') as file:
    model_testing_skf = pickle.load(file)
with open('Files/Pickle Files/data_cleaner.pkl', 'rb') as file:
    data_cleaner = pickle.load(file)

In [25]:
X = train.drop('TARGET_B', axis=1)
y = train['TARGET_B']

# Defining the Pipeline

We're first going to start by defining the pipeline we're gonna use as a base. This is the pipeline introduced in the Modeling Tools notebook, now with an MLPClassifier model.

In [26]:
# Categorical Feature Sub-Pipeline
# This is the part that handles the categorical columns, performing
# mode imputation, feature selection using our custom CategoricalFeatureSelector
# and finally one-hot encoding the features.
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('feature_selection',  CategoricalFeatureSelector()),
    # 3. Your specialized encoding (OneHot/Target) now receives imputed integers
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first')),
])

# Numerical Feature Sub-Pipeline
# Here we take care of our numerical features, starting with outlier clipping and feature
# creation using our custom transformer, then scaling data, so that it can then 
# be imputed and numerical feature selection can be performed
num_pipe = Pipeline([
    ('clipper', OutlierClipper()),
    ('feature_engineer', FeatureEngineer()),
    ('scaler', RobustScaler()),
    ('imputer', KNNImputer()),
    ('feature_selection', NumericalFeatureSelector(random_state=SEED))
])

# Here we use a ColumnTransformer with column selectors to perform the split
# between numerical and categorical data, so that each subset can be directed
# to the appropriate sub-pipeline
preprocessor = ColumnTransformer([
    ('cat_section', cat_pipe, make_column_selector(dtype_exclude=[np.number])),
    ('num_section', num_pipe, make_column_selector(dtype_include=[np.number])),
],
verbose_feature_names_out=False)
#  

 
# Final Pipeline
nn_pipe = Pipeline([
    ('cleaner', data_cleaner),
    ('preprocessing', preprocessor),
    ('model', TunedThresholdClassifierCV(MLPClassifier(random_state=SEED),
                                         n_jobs=-1,
                                         scoring='f1',
                                         random_state=SEED,
                                         cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)
                                         )) 
])

# We use the set_output to pandas so that intermediate transformers can use column
# names, since some of the default scikit-learn transformers by default return 
# Numpy arrays, which obviously don't have column names.
nn_pipe.set_output(transform="pandas")

Pipeline(steps=[('cleaner',
                 DataCleaner(categorical_cols_values={'DONOR_GENDER': ['M', 'F',
                                                                       'U'],
                                                      'INCOME_GROUP': array([1, 2, 3, 4, 5, 6, 7]),
                                                      'PEP_STAR': [0, 1],
                                                      'RECENCY_STATUS_96NK': ['S',
                                                                              'A',
                                                                              'E',
                                                                              'F',
                                                                              'N',
                                                                              'L'],
                                                      'RECENT_STAR_STATUS': [0,
                                                                             1],
                                                      'SES': array([1, 2, 3, 4, 5]),
                                                      'URBANICITY': ['S', 'T',
                                                                     'U', 'R',
                                                                     'C'],
                                                      'WEALTH_RATING': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])})),
                ('preprocessing',
                 Co...
                                                                  ('feature_selection',
                                                                   NumericalFeatureSelector(random_state=23))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001C39815C9B0>)],
                                   verbose_feature_names_out=False)),
                ('model',
                 TunedThresholdClassifierCV(cv=StratifiedKFold(n_splits=3, random_state=23, shuffle=True),
                                            estimator=MLPClassifier(random_state=23),
                                            n_jobs=-1, random_state=23,
                                            scoring='f1'))])

Now let's start looking at models and results.

# Single Hidden Layer Networks

We're going to start by testing one layer networs with up to 50 neurons.

```python
layer_size_list = np.arange(1, 50)
scores_train = []
scores_val = []
high_score=0
nof=0
for n_neurons in tqdm(layer_size_list):
    nn_single_layer_model = MLPClassifier((n_neurons), random_state=SEED)
    nn_single_layer_model.fit(X_train_preprocessed, y_train)
    train_pred = nn_single_layer_model.predict(X_train_preprocessed)
    val_pred = nn_single_layer_model.predict(X_val_preprocessed)
    scores_train.append(f1_score(y_train, train_pred))
    scores_val.append(f1_score(y_val, val_pred))
    if(f1_score(y_val, val_pred)>high_score):
        high_score = f1_score(y_val, val_pred)
        nof = layer_size_list[n_neurons-1]


print("Best Number of Neurons: %d" %nof)
print("F1 score in train with %d neurons: %f" % (nof, scores_train[nof-1]))
print("F1 score in validation with %d neurons: %f" % (nof, high_score))
```

![Single Layer Network Best](../Files/Images/NN_single_layer_best.png)

```python
plt.plot(layer_size_list, scores_train, label='Train')
plt.plot(layer_size_list, scores_val, label = 'Validation')
plt.vlines(x=nof,ymax=high_score,ymin=min(scores_val),ls='--',colors='g')
plt.xlabel('Number of Neurons')
plt.ylabel('score')
plt.legend()

plt.show()
```

![Single Layer Network Plot](../Files/Images/NN_single_layer_plot.png)

Overall the results are very poor with a high amount of overfitting, with a peak at 43.

# Single Hidden Layer Networks with Threshold optimization

Now, we'll analyze the impact of the threshold optimizer on single-layer networks of up to 50 neurons, the same as above.

```python
layer_size_list = np.arange(1, 50)
scores_train = []
scores_val = []
high_score=0
nof=0
for n_neurons in tqdm(layer_size_list):
    nn_single_layer_model = TunedThresholdClassifierCV(MLPClassifier((n_neurons), random_state=SEED),
                                         n_jobs=-1,
                                         scoring='f1',
                                         random_state=SEED,
                                         cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)
                                         )
    nn_single_layer_model.fit(X_train_preprocessed, y_train)
    train_pred = nn_single_layer_model.predict(X_train_preprocessed)
    val_pred = nn_single_layer_model.predict(X_val_preprocessed)
    scores_train.append(f1_score(y_train, train_pred))
    scores_val.append(f1_score(y_val, val_pred))
    if(f1_score(y_val, val_pred)>high_score):
        high_score = f1_score(y_val, val_pred)
        nof = layer_size_list[n_neurons-1]


print("Best Number of Neurons: %d" %nof)
print("F1 score in train with %d neurons: %f" % (nof, scores_train[nof-1]))
print("F1 score in validation with %d neurons: %f" % (nof, high_score))
```

![Single Layer Threshold Optimized Network Best](../Files/Images/NN_single_layer_opt_best.png)

```python
plt.plot(layer_size_list, scores_train, label='Train')
plt.plot(layer_size_list, scores_val, label = 'Validation')
plt.vlines(x=nof,ymax=high_score,ymin=min(scores_val),ls='--',colors='g')
plt.xlabel('Number of Neurons')
plt.ylabel('score')
plt.legend()

plt.show()
```

![Single Layer Threshold Optimized Network Plot](../Files/Images/NN_single_layer_opt_plot.png)

Adding the optimizer drastically improves results and now we have a peak at 7 neurons, indicating that with the help of the threshold optimizer this problem likely achieves best scores with simple networks.

# Two Hidden Layer Network

Since the single layer network achieved it's best results with 7 neurons, we're going to test a 2-layer network with structure (8, 4).

In [27]:
nn_2_layer_model = TunedThresholdClassifierCV(MLPClassifier((8, 4), random_state=SEED),
                                    n_jobs=-1,
                                    scoring='f1',
                                    random_state=SEED,
                                    cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)
                                    )
nn_2_layer_model.fit(X_train_preprocessed, y_train)
nn_2_layer_train_pred = nn_2_layer_model.predict(X_train_preprocessed)
nn_2_layer_val_pred = nn_2_layer_model.predict(X_val_preprocessed)
print(f"2 Hidden Layer Network Training F1-Score: {f1_score(y_train, nn_2_layer_train_pred)}")
print(f"2 Hidden Layer Network Validation F1-Score: {f1_score(y_val, nn_2_layer_val_pred)}")

2 Hidden Layer Network Training F1-Score: 0.4147834274952919
2 Hidden Layer Network Validation F1-Score: 0.40362953692115144

The scores are worse, so it seems the results are best when using single layer networks. We will test this basic 2 hidden layer option in our parameter search anyway for an added level of robustness.

# Activation Functions

An activation function in an MLPClassifier introduces non-linearity to the network, allowing it to learn complex, non-linear patterns rather than just straight lines. There are 4 options: 'identity', 'logistic', 'tanh' and 'relu'.

In [28]:
activation_f_list = ['identity', 'logistic', 'tanh', 'relu']
scores_train = []
scores_val = []
high_score=0
for function in activation_f_list:
    nn_single_layer_model = TunedThresholdClassifierCV(MLPClassifier((7), activation=function, random_state=SEED),
                                         n_jobs=-1,
                                         scoring='f1',
                                         random_state=SEED,
                                         cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=SEED)
    )
    nn_single_layer_model.fit(X_train_preprocessed, y_train)
    train_pred = nn_single_layer_model.predict(X_train_preprocessed)
    val_pred = nn_single_layer_model.predict(X_val_preprocessed)
    print("Activation function: {}".format(function))
    print("Mean F1 score in train: {}".format(f1_score(y_train, train_pred)))
    print("Mean F1 score in validation: {}\n".format(f1_score(y_val, val_pred)))

Activation function: identity
Mean F1 score in train: 0.42580768131135044
Mean F1 score in validation: 0.4068181818181818

Activation function: logistic
Mean F1 score in train: 0.4231059381398858
Mean F1 score in validation: 0.41229193341869397

Activation function: tanh
Mean F1 score in train: 0.4385598984311236
Mean F1 score in validation: 0.4044222539229672

Activation function: relu
Mean F1 score in train: 0.4494197391393653
Mean F1 score in validation: 0.41130684145841867

The logistic and relu activation functions performed much better than the other 2 options, as such we'll test those 2 options and not the other two.

# Parameter Search

We're going to test several combinations across our grid to optimize our preprocessing and modeling steps efficiently. This is because neural networks are highly sensitive to data scaling, meaning standard interval scalers will be tested alongside the distance-based imputer, while the solver and regularization combinations will be isolated to find the most stable optimization path:

+ In preprocessing:
    + Scaler: We are going to test three scaling methodologies: PowerTransformer, MinMaxScaler, and RobustScaler (which scales via quartile values to mitigate outlier weight distortion). The PowerTransformer applies variance-stabilizing transformations to bring feature distributions close to a Gaussian Normal distribution before standardizing them to a mean of 0 and variance of 1, just like StandardScaler would.
    + Imputer: We will only use the distance-based KNNImputer configured with 50 neighbors to allow us to test more model parameter combinations.
    + Clipping: Three outlier-handling approaches are tested across the combinations: no clipping at all (None), and clipping based on the IQR method for both normal and extreme outliers following normal convention of 1.5 and 3 times IQR beyond the quartiles, respectively.

+ In the model (early stopping, and a max of 300 iterations):
    + Solvers: We are only testing the adam (an adaptive gradient-descent optimizer) solver to leave more room for other parameter options, we exclude sgd, since it often requires much more refined tuning and lbfgs since it can struggle to converge well on larger data sets. The sklearn documentation itself mentions adam as a solid option for balancing the compromise between runtime and performance.
    + Hidden Layer Sizes: Guided by preliminary validation curves showing an early peak followed by severe overfitting, we are focusing primarily on single-layer micro-architectures with widths of 6, 7, and 8 neurons, while also introducing two small multi-layer option (8,4) to test basic deep representation capabilities.
    + Alpha Regularization: To control weight inflation and eliminate the high-variance fluctuations observed in the initial validation runs, we are searching across alpha values spanning from 0.01 up to an aggressive 5.0 (specifically testing 0.01, 0.1, 1.0, and 5.0).
    + Activation Functions: We're aiming to reach as many combinations as possible by also including two different activation functions, based on our findings above.

In [29]:
param_grid = {
    'preprocessing__num_section__scaler' : [PowerTransformer(), MinMaxScaler(), RobustScaler()], 
    'preprocessing__num_section__imputer' : [KNNImputer(n_neighbors=50)], 
    'preprocessing__num_section__clipper' : [None, OutlierClipper(method='iqr', iqr_multiplier=1.5), OutlierClipper(method='iqr', iqr_multiplier=3)],
    'model__estimator' : [MLPClassifier(activation='relu', early_stopping=True, max_iter=300, random_state=SEED)],
    'model__estimator__activation' : ['relu', 'logistic'],
    'model__estimator__solver' : ['adam'],
    'model__estimator__hidden_layer_sizes' : [(6,), (7,), (8,), (8, 4)],
    'model__estimator__alpha' : [0.01, 0.1, 1.0, 5.0]
}

```python
run_parameter_search(grid=param_grid,
                     cv=model_testing_skf, 
                     X=X, y=y,
                     model=nn_pipe,
                     metrics=['f1', 'precision', 'recall'],
                     results_file_dir='Files/Pickle Files/Results/NN_GridSearch_Results.pkl',
                     model_file_dir='Files/Pickle Files/Pipelines/NN_GridSearch_Best_Pipeline.pkl',
                     refit=True,
                     n_jobs=-1)

In [30]:
nn_result_df = pd.read_pickle('Files/Pickle Files/Results/NN_GridSearch_Results.pkl')
nn_result_df.head()

,params_config,model__estimator,model__estimator__activation,model__estimator__alpha,model__estimator__hidden_layer_sizes,model__estimator__solver,preprocessing__num_section__clipper,preprocessing__num_section__imputer,preprocessing__num_section__scaler,mean_fit_time,mean_val_f1,std_val_f1,mean_train_f1,std_train_f1,mean_val_precision,std_val_precision,mean_train_precision,std_train_precision,mean_val_recall,std_val_recall,mean_train_recall,std_train_recall,status
126,{'model__estimator': MLPClassifier(activation=...,"MLPClassifier(activation='logistic', alpha=5.0...",relu,5.00,"(8,)",adam,None,KNNImputer(n_neighbors=50),PowerTransformer(),84.402186,0.418193,0.003329,0.421301,0.002857,0.287552,0.004181,0.289770,0.005102,0.767552,0.026476,0.772493,0.019595,Success
98,{'model__estimator': MLPClassifier(activation=...,"MLPClassifier(activation='logistic', alpha=5.0...",relu,1.00,"(8,)",adam,OutlierClipper(iqr_multiplier=3),KNNImputer(n_neighbors=50),RobustScaler(),71.020751,0.417471,0.007472,0.420332,0.004534,0.283659,0.007249,0.285510,0.003827,0.791150,0.017909,0.798156,0.037254,Success
78,{'model__estimator': MLPClassifier(activation=...,"MLPClassifier(activation='logistic', alpha=5.0...",relu,1.00,"(6,)",adam,OutlierClipper(iqr_multiplier=3),KNNImputer(n_neighbors=50),PowerTransformer(),51.757369,0.416598,0.002440,0.423759,0.008650,0.280455,0.007120,0.285325,0.010583,0.813274,0.043027,0.826327,0.031670,Success
62,{'model__estimator': MLPClassifier(activation=...,"MLPClassifier(activation='logistic', alpha=5.0...",relu,0.10,"(8,)",adam,OutlierClipper(iqr_multiplier=3),KNNImputer(n_neighbors=50),RobustScaler(),71.695753,0.416299,0.010387,0.421336,0.005700,0.284314,0.004748,0.287455,0.005373,0.779056,0.048555,0.789823,0.027471,Success
17,{'model__estimator': MLPClassifier(activation=...,"MLPClassifier(activation='logistic', alpha=5.0...",relu,0.01,"(7,)",adam,OutlierClipper(iqr_multiplier=3),KNNImputer(n_neighbors=50),RobustScaler(),70.470558,0.415983,0.006392,0.418031,0.007277,0.278628,0.010463,0.279612,0.009864,0.827139,0.057324,0.834661,0.063010,Success

In [31]:
nn_result_df.iloc[0]['params_config']

{'model__estimator': MLPClassifier(activation='logistic', alpha=5.0, early_stopping=True,
               hidden_layer_sizes=(8, 4), max_iter=300, random_state=23),
 'model__estimator__activation': 'relu',
 'model__estimator__alpha': 5.0,
 'model__estimator__hidden_layer_sizes': (8,),
 'model__estimator__solver': 'adam',
 'preprocessing__num_section__clipper': None,
 'preprocessing__num_section__imputer': KNNImputer(n_neighbors=50),
 'preprocessing__num_section__scaler': PowerTransformer()}

In [32]:
with open('Files/Pickle Files/Pipelines/NN_GridSearch_Best_Pipeline.pkl', 'rb') as file:
    nn_best_pipeline = pickle.load(file)

In [33]:
nn_best_pipeline['model'].best_threshold_

np.float64(0.21659308142523703)

The best parameter combination achieved a mean validation F1-score of 0.418193 and a mean training F1-score of 0.421302 indicating no severe over or under fitting. It used the PowwerTransformer and the KNNImputer. The model used a single 8 Neuron hidden layer Network, with the adam solver, relu activation function and alpha of 5.

Additionally, it has an optimized decision threshold of ~0.22 which means it allows for significantly more predicted positives, in other words predicts many more donations than if it were using the default threshold. This means that the recall is higher using this threshold which means that the model is finding a higher rate of the true donors. This comes with the side effect of also sending the campaign to more people who won't donate (False Postives) lowering precision. But as the goal is to maximize donations while optimizing the campaign distribution process, this seems like a decent compromise.

# Test Set Prediction

The last thing to do is to predict for the test set, for our deployment simulation. For that we'll generate the prediction and export it to a CSV file as instructed.

In [34]:
nn_pred_test = pd.DataFrame(nn_best_pipeline.predict(test), index=test['CONTROL_NUMBER'], columns=['TARGET_B'])
nn_pred_test

                TARGET_B
CONTROL_NUMBER
122653                 0
184239                 1
5172                   1
135377                 1
62119                  1
...                  ...
54438                  1
122194                 1
106603                 1
123603                 1
65406                  1

[5812 rows x 1 columns]

In [35]:
nn_pred_test.to_csv('Files/Submissions/DM2DT_Group12_Version29.csv')

The best model from the Neural Network parameter search achieves an F1-Score of 0.43264 as the public score on Kaggle. We also add this score to the kaggle results file and then re-export it, with the cv scores directly from the dataframe.

In [36]:
kaggle_results_df = pd.read_pickle('Files/Pickle Files/Kaggle_scores.pkl')

In [37]:
kaggle_results_df.loc['Best NN Pipeline'] = [0.43264, 'DM2DT_Group12_Version29.csv', nn_result_df.iloc[0]['mean_val_f1'], nn_result_df.iloc[0]['mean_train_f1']]

In [38]:
kaggle_results_df

,Kaggle Public Score,Submission File Name,CV Mean Val F1,CV Mean Train F1
Best DT Pipeline,0.41582,DM2DT_Group12_Version19.csv,0.411342,0.415477
Best KNN Pipeline,0.42145,DM2DT_Group12_Version18.csv,0.410642,0.431648
Best NB Pipeline,0.42893,DM2DT_Group12_Version20.csv,0.419758,0.419638
Best LR Pipeline,0.43087,DM2DT_Group12_Version25.csv,0.421687,0.423902
Best RF Pipeline,0.43304,DM2DT_Group12_Version22.csv,0.421884,0.461440
Best AdaBoost Pipeline,0.43735,DM2DT_Group12_Version23.csv,0.412953,0.416364
Best GB Pipeline,0.43478,DM2DT_Group12_Version24.csv,0.420412,0.466219
Best NN Pipeline,0.43264,DM2DT_Group12_Version29.csv,0.418193,0.421301

In [39]:
kaggle_results_df.to_pickle('Files/Pickle Files/Kaggle_scores.pkl')